/**
 * Centralized Legal Information Disclaimers
 * Mandatory notices to maintain ethical and regulatory boundaries.
 * Must be referenced across UI, API, alternatives, negotiation briefs, and exports.
 */

export const GLOBAL_LEGAL_DISCLAIMER =
  'INFORMATIONAL ONLY: JuriLens assists in understanding contract provisions. It does not provide legal advice, legal opinion, or attorney representation. Consult qualified legal counsel for binding legal decisions.';

export const ALTERNATIVE_CLAUSE_DISCLAIMER =
  'Illustrative Drafting Suggestion — Not Formal Counsel';

export const EXPORT_PREAMBLE_DISCLAIMER =
  'NOTICE: This document analysis is generated by JuriLens ClauseRadar for informational and organizational assistance only. It does not constitute legal representation, legal advice, or statutory legal opinions. The observations and suggested negotiation alternatives reflect automated semantic document analysis and must be reviewed by a qualified legal professional before reliance or execution.';

export const SHORT_DISCLAIMER = 'Information only — Not legal advice';
